# version: '3.8'

services:
  
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data/db
    networks:
      - mba_aula_nosql
  
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mba_aula_nosql

  Scylla:
    image: scylladb/scylla:latest
    container_name: scylla_container
    ports:
      - "9042:9042"
    volumes:
      - scylla_data:/var/lib/scylladb
    networks:
      - mba_aula_nosql  
  

  neo4j:
    image: neo4j:latest
    container_name: neo4j_container
    ports:
    - "7474:7474"
    - "7687:7687"
    volumes:
    - neo4j_data:/data/db
    networks:
    - mba_aula_nosql
    environment:
    - NEO4J_AUTH=neo4j/aluno123
    - NEO4J_dbms_memory_heap_max__size=512m
  
volumes:
  redis_data:
  mongo_data:
  scylla_data:
  neo4j_data:
  #cassandra_data:


networks:
  mba_aula_nosql:
    driver: bridge
